/*
 * This source file was generated by the Gradle 'init' task
 */
package net.ronsconsulting;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertNotNull;

public class AppTest {
    @Test 
    public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull((Object) classUnderTest.getGreeting(), "app should have a greeting");
    }
}
